### PR TITLE
Fix Bugs Reported in Issue#13

### PR DESCRIPTION
**Pull request by tswwe**
This patch addresses the bugs reported in [Issue#13](https://github.com/phibr0/obsidian-emoji-shortcodes/issues/13).
Note: Because I don't have a typescript compiler, these changes are made base on [my local modified *.obsidian/plugins/emoji-shortcodes/main.js* file](https://github.com/phibr0/obsidian-emoji-shortcodes/files/7070745/modified-main-js.zip), which is proved to work for me. Anyway, further test may be needed.

### CODE REVIEW

**Comment by phibr0** [comment]
Looks good, will test it before merge

**Comment by phibr0** [comment]
Okay everything works great, except when you press Enter in the Suggester it will insert the currently selected Emoji **and** go to the next line (because of the Enter key press). Any obvious way to "only eat the Enter keypress, when a emoji is entered"?

**Comment by tswwe** [comment]
Thank you for reviewing and find out the case I ignored. I have push a new commit to the *patch-issue#13-tswwe* branch to fix it. To be specific, the new commit just adds one line (`return false;`) into line#84 in *suggest.ts*.

**Comment by phibr0** [comment]
I will create the Release later today

**Pull request merged**
