### PR TITLE
Implement suggestion history priority

### PR DESCRIPTION
**Pull request by usagizmo**
I implemented to show recently used emojis preferentially.

CleanShot 2022-12-09 at 04 13 51
CleanShot 2022-12-09 at 04 14 03

#31 #33 #34

### CODE REVIEW

**Comment by phibr0** [comment]
Thats a great idea, but maybe limit the amount of emojis in the history list (and maybe make it toggleable in the settings?)

**Comment by usagizmo** [comment]
Ok. I'll try it.
I'll leave the English wording on the settings to you.

**Comment by usagizmo** [comment]
DONE.

**Comment by phibr0** [comment]
Oh I actually meant the feature as a whole to be toggleable, but its fine I can work on that (later next weekend)

**Comment by usagizmo** [comment]
I adjusted the settings.

CleanShot 2022-12-11 at 12 31 18

**Comment by phibr0** [comment]
Thank you! Thats perfect.

**Pull request merged**
